[profile.lite]
src = "src"
out = 'out'
libs = ['lib']
remappings = []
solc_version = "0.8.26"
evm_version = "cancun"
optimizer_runs = 200
ignored_error_codes = [1878]
bytecode_hash="ipfs"
rpc_storage_caching = { chains = "all", endpoints = "remote" }
fuzz_runs = 5

[profile.test]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = false
evm_version = "cancun"
solc = "0.8.26"
verbosity = 2
ffi = true

[profile.default.invariant]
runs = 16
depth = 256
fail_on_revert = true

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 999999
via_ir = true
evm_version = "cancun"
solc = "0.8.26"
verbosity = 2
ffi = true

remappings = [
  "forge-std=lib/forge-std/src",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
"@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

[fmt]
line_length = 160
number_underscore = "thousands"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "${MAINNET_API_KEY}"
sepolia = "${SEPOLIA_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config